<?php

namespace FraterSoft\PiaWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventoRepository extends EntityRepository
{
    public function buscarPorEmailOrganizador($email)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e FROM FraterSoftPiaWebBundle:Evento e WHERE e.emailcontacto ="' . $email . '"'
            )
            ->getResult();
    }

    public function listaPorEmailCompetidor($email)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT i FROM FraterSoftPiaWebBundle:Inscrito i '
                    . 'JOIN i.idpia c '
                    . 'WHERE c.email =\'' . $email . '\''
            )
            ->getResult();
    } 
    
    public function edadMinima($idevento)
    {
        return $this->getEntityManager()
            ->createQuery(
                'select min(cr.valor1) from FraterSoftPiaWebBundle:CategoriaReglas cr '
                    . 'where cr.atributo=\'Edad\' and cr.idcategoria in  '
//                    . '(select c.id from FraterSoftPiaWebBundle:Categoria c where c.idevento=' . $idevento . ')'
                    . '(select ca.id from FraterSoftPiaWebBundle:Evento ev inner join FraterSoftPiaWebBundle:Competencia co WITH ev.id = co.idevento inner join FraterSoftPiaWebBundle:Categoria ca WITH co.id = ca.idcompetencia
where ev.id=' . $idevento . ')'
            )
            ->getResult()[0][1];
    }     
}
