<?php

namespace FraterSoft\PiaWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrecioscategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormaspagoRepository extends EntityRepository {

    public function listar($idevento) {
        //Busca el precio por fecha hasta
        $formaspago = $this->getEntityManager()
                ->createQuery(
                        "select fp from FraterSoftPiaWebBundle:Formaspago fp "
                        //. "FraterSoftPiaWebBundle:Formaspagoevento fpe "
                        . "inner join fpe.idformapagoevento fpe "
                        . "where fpe.idevento = " . $idevento 
                        
                )
                ->getResult();
        return $formaspago;
    }

}
