<?php

namespace FraterSoft\PiaWebBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * ListaseventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListaseventoRepository extends EntityRepository {

    public function getArrayValores($idevento,$idatributo) {
        $valores = array();
        $lista = $this->getEntityManager()
                ->createQuery(
                        "select le.codigo, le.valor, le.limite from FraterSoftPiaWebBundle:Listasevento le "
                        . "where le.idevento = " . $idevento . " and le.idatributo=" . $idatributo 
                        . " order by le.codigo"
                )
                ->getResult();
        foreach($lista as $valor){
            //$valores[$valor['codigo']]=$valor['valor'];
            if(is_null($valor['limite']))
                $valores[$valor['codigo']]=$valor['valor'];
            else if($valor['limite']>0)
                $valores[$valor['codigo']]=$valor['valor'];            
        }
        return $valores;
    }
    
    public function arrayListasEvento($idevento)
    {
        return $this->getEntityManager()
            ->createQuery(
                "select le.id, e.id as idevento,a.id as idatributo, le.codigo, le.valor, le.limite from FraterSoftPiaWebBundle:Listasevento le "
                    . "JOIN le.idevento e "
                    . "JOIN le.idatributo a "
                . "where le.idevento = " . $idevento 
            )
            ->getResult();
    }
    
    public function atributosConLimites($idevento){
        return $this->getEntityManager()
            ->createQuery(
                "select le.id, e.id as idevento,a.id as idatributo, a.nombre as nombre, le.codigo, le.valor, le.limite from FraterSoftPiaWebBundle:Listasevento le "
                    . "JOIN le.idevento e "
                    . "JOIN le.idatributo a "
                . "where le.idevento = " . $idevento . " and a.tipodato='O' and le.limite is not null"
            )
            ->getResult();
    }    

}