<?php

namespace FraterSoft\PiaWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrecioscategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonedaRepository extends EntityRepository {
    
    public function listarMonedasEvento($idevento) {
        //Busca el precio por fecha hasta
        $formaspago = $this->getEntityManager()
                ->createQuery(
                        "select fpe.idformapago.idmoneda from FraterSoftPiaWebBundle:Formaspagoevento fpe "
                        . "join fpe.idformapago fp "
                        . "join fp.idmoneda m "
                        . "where fpe.idevento = " . $idevento . " and fpe.publico=true and fpe.status=1"
                )
                ->getResult();
        return $formaspago;
    }  

    public function arrayMonedasEvento($idevento)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT fpe.id,e.id as idevento,fp.id as idformapago,fp.nombre as nombre,fpe.status,fpe.incremento,fpe.publico, m.nombre as moneda '
                    . 'FROM FraterSoftPiaWebBundle:Formaspagoevento fpe ' 
                    . 'JOIN fpe.idformapago fp '                  
                    . 'JOIN fp.idmoneda m '
                    . 'JOIN fpe.idevento e '                  
                    . 'WHERE fpe.publico=true and fpe.status=1 and fpe.idevento =' . $idevento 
            );
         return $query->getResult();
    }              

    public function MonedasEnEvento($idevento)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT DISTINCT m.id, m.nombre,m.idpais '
                    . 'FROM FraterSoftPiaWebBundle:Formaspagoevento fpe ' 
                    . 'JOIN fpe.idformapago fp '                  
                    . 'JOIN fp.idmoneda m '
                    . 'JOIN fpe.idevento e '                  
                    . 'WHERE fpe.publico=true and fpe.status=1 and m.estatus=1 and fpe.idevento =' . $idevento 
            );
         return $query->getResult();
    }              
    
}