<?php

namespace FraterSoft\PiaWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrecioscategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumeracionRepository extends EntityRepository {

    public function resetear($idevento) {
        $formaspago = $this->getEntityManager()
                ->createQuery(
                        "update FraterSoftPiaWebBundle:Inscrito i SET i.numero=NULL "
                        . "where i.idevento = " . $idevento 
                )
                ->getArrayResult();
        return $formaspago;
    }

}
