<?php

namespace FraterSoft\PiaWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrecioscategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumeracionexternaRepository extends EntityRepository {

    public function resetear($idnumeracion) {
        return $this->getEntityManager()
            ->createQuery(
                'Update FraterSoftPiaWebBundle:Numeracionexterna ne '
                    . 'SET ne.asignado=false '
                    . 'WHERE ne.idnumeracion= ' . $idnumeracion
            )
            ->execute();    
    }
}
