<?php

namespace FraterSoft\PiaWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrecioscategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganizadorRepository extends EntityRepository {

    
    public function eventosPubilidadPatrocinantePorEmail($email)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT '                
            	. 'e.logo,e.id,e.nombre,e.fecha,e.fechacierre,e.cupomaximo,e.activo, '
            	. '(select count(i.id) from FraterSoftPiaWebBundle:Inscrito i left join FraterSoftPiaWebBundle:Pago p with p.idinscrito=i.id where i.idevento=e.id and i.status=1 and (p.id is null or p.conciliado is null) as preinscritos, '
            	. '(select count(j.id) from FraterSoftPiaWebBundle:Inscrito j left join FraterSoftPiaWebBundle:Pago q with q.idinscrito=j.id where j.idevento=e.id and q.conciliado = true and j.status=1) as inscritos, '
            	. '(select count(k.id) from FraterSoftPiaWebBundle:Inscrito k left join FraterSoftPiaWebBundle:Pago r with r.idinscrito=k.id where k.idevento=e.id and r.conciliado is null and k.status=1 and r.tipo=\'3\') as tdcsinpago '
                . 'FROM FraterSoftPiaWebBundle:Organizador o '
                        . 'INNER FROM FraterSoftPiaWebBundle:Patrocinante pa with pa.idorganizador = o.id ' 
                        . 'INNER JOIN FraterSoftPiaWebBundle:Publicidad pu with pu.idpatrocinante = pa.id '
                        . 'INNER JOIN FraterSoftPiaWebBundle:Evento e with pu.idevento = e.id '
                . 'WHERE o.email = \'' . $email . '\''
            );
         return $query->getResult();
    }          

    public function listaIdsEventosPatrocinadosPorEmail($email)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT '                
            	. 'e.id '
                . 'FROM FraterSoftPiaWebBundle:Organizador o '
                        . 'INNER FROM FraterSoftPiaWebBundle:Patrocinante pa with pa.idorganizador = o.id ' 
                        . 'INNER JOIN FraterSoftPiaWebBundle:Publicidad pu with pu.idpatrocinante = pa.id '
                        . 'INNER JOIN FraterSoftPiaWebBundle:Evento e with pu.idevento = e.id '
                . 'WHERE o.email = \'' . $email . '\''
            );
         return $query->getResult();
    }          
    
}
