<?php

namespace FraterSoft\PiaWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrecioscategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatrocinanteRepository extends EntityRepository {

    /*
     * Llena el dattable del twig. En valor devuelo debe ser un array json simple, No deben haber objetos anidados
     * para lo cual se deben detallar los campos a mostrar en la tabla
    */
    public function arrayListas($idorganizador)
    {
        return $this->getEntityManager()
            ->createQuery(
                "select p.id,p.logo,p.nombre,p.estatus,o.id as idorganizador  from FraterSoftPiaWebBundle:Patrocinante p "
                    . "JOIN p.idorganizador o "
                . "where p.idorganizador  = " . $idorganizador
            )
            ->getResult();
    }
    

}
