<?php

namespace FraterSoft\PiaWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrecioscategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumeracionRepository extends EntityRepository {

    public function resetear($idevento) {
        $formaspago = $this->getEntityManager()
                ->createQuery(
                        "update FraterSoftPiaWebBundle:Inscrito i SET i.numero=NULL "
                        . "where i.idevento = " . $idevento 
                )
                ->getArrayResult();
        return $formaspago;
    }
    
    public function arrayListas($idevento)
    {
        return $this->getEntityManager()
            ->createQuery(
                "select nu.id, e.id as idevento, nu.inicio, nu.fin, nu.siguiente, nu.ordenarpor, nu.secuencial, nu.atributo from FraterSoftPiaWebBundle:Numeracion nu "
                    . "JOIN nu.idevento e "
                . "where nu.idevento = " . $idevento 
            )
            ->getResult();
    }
    

}
