<?php

namespace FraterSoft\PiaWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrecioscategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatrocinanteRepository extends EntityRepository {

    public function arrayListas($idorganizador)
    {
        return $this->getEntityManager()
            ->createQuery(
                "select entity from FraterSoftPiaWebBundle:Patrocinante entity "
                    . "JOIN entity.idorganizador o "
                . "where entity.idorganizador  = " . $idorganizador
            )
            ->getResult();
    }
    

}
