<?php

namespace FraterSoft\PiaWebBundle\Entity;
use Doctrine\Common\Collections\ArrayCollection;

use Doctrine\ORM\EntityRepository;

/**
 * PrecioscompetenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrecioscompetenciaRepository extends EntityRepository {
    /*     * **
     * El sistema evalua primero el precio por cantidad, luego lo hace por fecha.
     * Es importante qie si el evento se va a confiurar sus precios por cantidades
     * El ultimo precio debe estar por fecha, la cual debe ser igual a la fecha de 
     * cierre del evento
     * ** */

    public function BuscaPreciosCompetencia($idcompetencia){
        $precios = $this->getEntityManager()
            ->createQuery(
                    "select p.cantidad, p.precio, p.hasta, c.descripcion as texto, 'Bs' as moneda "
                    . "from FraterSoftPiaWebBundle:Precioscompetencia p join p.idcompetencia c "
                    . "where p.idcompetencia=c.id and p.idcompetencia = " . $idcompetencia 
                    . " order by p.precio"
            )
            ->getResult();        
        $preciosselect = new ArrayCollection();
        $imagenanterior = "vacio";
        foreach($precios as $precio){
            switch(true){
                //Solo cantidad configurada
                case !is_null($precio['cantidad']) && is_null($precio['hasta']):
                    $inscritos = $this->getEntityManager()
                        ->createQuery(
                            "select count(i.id) as inscritos from FraterSoftPiaWebBundle:Inscrito i "
                            . "where i.idcompetencia=" . $idcompetencia . " and i.precio = " . $precio['precio']
                        )
                    ->getResult();
                    if($precio['cantidad']>$inscritos[0]['inscritos']){
                        $preciosselect->add($precio);
                        break 2;
                    }
                    break;
                //Solo fecha configurada
                case is_null($precio['cantidad']) && !is_null($precio['hasta']):
                    if($precio['hasta'] >= new \DateTime('now')){
                        $preciosselect->add($precio);
                        break 2;
                    }
                    break;
                //Cantidad y fecha configurada
                case !is_null($precio['cantidad']) && !is_null($precio['hasta']):
                    $inscritos = $this->getEntityManager()
                        ->createQuery(
                            "select count(i.id) as inscritos from FraterSoftPiaWebBundle:Inscrito i "
                            . "where i.idcompetencia=" . $idcompetencia . " and i.precio = " . $precio['precio']
                        )
                    ->getResult();       
                    if($precio['cantidad'] > $inscritos[0]['inscritos'] && $precio['hasta'] >= new \DateTime('now')){
                        $preciosselect->add($precio);
                        break 2;
                    }
                    break;
                //Ninguno configurados configurados
                case is_null($precio['cantidad']) && is_null($precio['hasta']):
                    $preciosselect->add($precio);
                    break;
            }
        }
        return($preciosselect);
    }
    
    public function arrayPrecios($idevento)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT pc.id,c.id as idcompetencia,pc.precio,pc.cantidad,pc.hasta,pc.prioridad,pc.texto,pc.imagen,pc.moneda '
                    . 'FROM FraterSoftPiaWebBundle:Precioscompetencia pc ' 
                    . 'JOIN pc.idcompetencia c '                  
                    . 'WHERE c.idevento =' . $idevento 
            );
         return $query->getResult();
    }       
}
