<?php

namespace FraterSoft\PiaWebBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * PrecioscategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrecioscategoriaRepository extends EntityRepository {

    public function BuscaPreciosCategoria($idcategoria){
        $precios = $this->getEntityManager()
            ->createQuery(
                    "select p.cantidad, p.precio, p.hasta, p.imagen, p.texto, p.moneda "
                    . "from FraterSoftPiaWebBundle:Precioscategoria p "
                    . "where p.idcategoria = " . $idcategoria 
                    . " order by p.precio"
            )
            ->getResult();        
        $preciosselect = new ArrayCollection();
        $imagenanterior = "vacio";
        foreach($precios as $precio){
            switch(true){
                //Solo cantidad configurada
                case !is_null($precio['cantidad']) && is_null($precio['hasta']):
                    $inscritos = $this->getEntityManager()
                        ->createQuery(
                            "select count(i.id) as inscritos from FraterSoftPiaWebBundle:Inscrito i "
                            . "where i.idcategoria=" . $idcategoria . " and i.precio = " . $precio['precio']
                        )
                    ->getResult();
                    if($precio['cantidad']>$inscritos[0]['inscritos']){
                        $preciosselect->add($precio);
                        break 2;
                    }
                    break;
                //Solo fecha configurada
                case is_null($precio['cantidad']) && !is_null($precio['hasta']):
                    if($precio['hasta'] >= new \DateTime('now')){
                        $preciosselect->add($precio);
                        break 2;
                    }
                    break;
                //Cantidad y fecha configurada
                case !is_null($precio['cantidad']) && !is_null($precio['hasta']):
                    $inscritos = $this->getEntityManager()
                        ->createQuery(
                            "select count(i.id) as inscritos from FraterSoftPiaWebBundle:Inscrito i "
                            . "where i.idcategoria=" . $idcategoria . " and i.precio = " . $precio['precio']
                        )
                    ->getResult();       
                    if($precio['cantidad'] > $inscritos[0]['inscritos'] && $precio['hasta'] >= new \DateTime('now')){
                        $preciosselect->add($precio);
                        break 2;
                    }
                    break;
                //Ninguno configurados configurados
                case is_null($precio['cantidad']) && is_null($precio['hasta']):
                    $preciosselect->add($precio);
                    break;
            }
        }
        return($preciosselect);
    }
    
    public function arrayPrecios($idevento)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT pc.id,ca.id as idcategoria, co.id as idcompetencia, ca.descripcion as nombre, pc.precio,pc.cantidad,pc.hasta,pc.prioridad,pc.texto,pc.imagen,pc.moneda '
                    . 'FROM FraterSoftPiaWebBundle:Precioscategoria pc ' 
                    . 'JOIN pc.idcategoria ca '                  
                    . 'JOIN ca.idcompetencia co '                  
                    . 'WHERE co.idevento =' . $idevento 
            );
         return $query->getResult();
    }       

}
