<?php

namespace FraterSoft\PiaWebBundle\Entity;
use Doctrine\Common\Collections\ArrayCollection;

use Doctrine\ORM\EntityRepository;

/**
 * PrecioscompetenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrecioscompetenciaRepository extends EntityRepository {
    /*     * **
     * El sistema evalua primero el precio por cantidad, luego lo hace por fecha.
     * Es importante qie si el evento se va a confiurar sus precios por cantidades
     * El ultimo precio debe estar por fecha, la cual debe ser igual a la fecha de 
     * cierre del evento
     * ** */

//    public function buscarPrecioActivo($idcompetencia) {
//        //Busca el precio por fecha hasta
//        $preciocantidad = $this->getEntityManager()
//                ->createQuery(
//                        "select p.precio from FraterSoftPiaWebBundle:Precioscompetencia p "
//                        . "where p.idcompetencia = " . $idcompetencia . " and p.cantidad = "
//                        . "(SELECT min(c.cantidad) FROM FraterSoftPiaWebBundle:Precioscompetencia c "
//                        . "WHERE c.idcompetencia = " . $idcompetencia . " AND c.cantidad > "
//                        . "(select count(i.id) from FraterSoftPiaWebBundle:Inscrito i "
//                        . "where i.idcompetencia=" . $idcompetencia . "))"
//                )
//                ->getResult();
//
//        $preciofecha = $this->getEntityManager()
//                ->createQuery(
//                        "select p.precio from FraterSoftPiaWebBundle:Precioscompetencia p "
//                        . "where p.idcompetencia = " . $idcompetencia . " and p.hasta = "
//                        . "(SELECT min(h.hasta) FROM FraterSoftPiaWebBundle:Precioscompetencia h "
//                        . "WHERE h.idcompetencia = " . $idcompetencia . " AND h.hasta >= CURRENT_TIMESTAMP())"
//                )
//                ->getResult();
//        
//        if (!$preciocantidad) //Si el precio por cantidad es nulo, devuelvo precio fecha
//            return $preciofecha;
//        if (!$preciofecha) //Si el precio por fecha es nulo, devuelvo precio cantidad
//            return $preciocantidad;
//        if (!$preciocantidad && !$preciofecha) //Si ambos son nulos, devuelvo 0
//            return null;
//        if ($preciocantidad >= $preciofecha) //Si el precio por cantidad es mayor que el precio por fecha, devuelvo precio cantidad
//            return $preciocantidad;
//        if ($preciofecha >= $preciocantidad) //Si el precio por cantidad es menor que el precio por fecha, devuelvo precio cantidad
//            return $preciofecha;
//        return null;
//    }

    public function BuscaPreciosCompetencia($idcompetencia){
        $precios = $this->getEntityManager()
            ->createQuery(
                    "select p.cantidad, p.precio, p.hasta, c.descripcion as texto, 'Bs' as moneda "
                    . "from FraterSoftPiaWebBundle:Precioscompetencia p join p.idcompetencia c "
                    . "where p.idcompetencia=c.id and p.idcompetencia = " . $idcompetencia 
                    . " order by p.precio"
            )
            ->getResult();        
        $preciosselect = new ArrayCollection();
        $imagenanterior = "vacio";
        foreach($precios as $precio){
            switch(true){
                //Solo cantidad configurada
                case !is_null($precio['cantidad']) && is_null($precio['hasta']):
                    $inscritos = $this->getEntityManager()
                        ->createQuery(
                            "select count(i.id) as inscritos from FraterSoftPiaWebBundle:Inscrito i "
                            . "where i.idcompetencia=" . $idcompetencia . " and i.precio = " . $precio['precio']
                        )
                    ->getResult();
                    if($precio['cantidad']>$inscritos[0]['inscritos']){
                        $preciosselect->add($precio);
                        break 2;
                    }
                    break;
                //Solo fecha configurada
                case is_null($precio['cantidad']) && !is_null($precio['hasta']):
                    if($precio['hasta'] >= new \DateTime('now')){
                        $preciosselect->add($precio);
                        break 2;
                    }
                    break;
                //Cantidad y fecha configurada
                case !is_null($precio['cantidad']) && !is_null($precio['hasta']):
                    $inscritos = $this->getEntityManager()
                        ->createQuery(
                            "select count(i.id) as inscritos from FraterSoftPiaWebBundle:Inscrito i "
                            . "where i.idcompetencia=" . $idcompetencia . " and i.precio = " . $precio['precio']
                        )
                    ->getResult();       
                    if($precio['cantidad'] > $inscritos[0]['inscritos'] && $precio['hasta'] >= new \DateTime('now')){
                        $preciosselect->add($precio);
                        break 2;
                    }
                    break;
                //Ninguno configurados configurados
                case is_null($precio['cantidad']) && is_null($precio['hasta']):
                    $preciosselect->add($precio);
                    break;
            }
        }
        return($preciosselect);
    }
    
    public function arrayPreciosEvento($idevento)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT pc.id,c.id as idcompetencia,pc.precio,pc.cantidad,pc.hasta,pc.prioridad,pc.texto,pc.imagen,pc.moneda '
                    . 'FROM FraterSoftPiaWebBundle:Precioscompetencia pc ' 
                    . 'JOIN pc.idcompetencia c '                  
                    . 'WHERE c.idevento =' . $idevento 
            );
         return $query->getResult();
    }       
}
