<?php

namespace FraterSoft\PiaWebBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * PrecioseventoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrecioseventoRepository extends EntityRepository {
    /*     * **
     * El sistema evalua primero el precio por cantidad, luego lo hace por fecha.
     * Es importante qie si el evento se va a confiurar sus precios por cantidades
     * El ultimo precio debe estar por fecha, la cual debe ser igual a la fecha de 
     * cierre del evento
     */

    public function buscarPrecioActivo($idevento) {
        //Busca el precio por fecha hasta
        $preciocantidad = $this->getEntityManager()
                ->createQuery(
                        "select p.precio from FraterSoftPiaWebBundle:Preciosevento p "
                        . "where p.idevento = " . $idevento . " and p.cantidad = "
                        . "(SELECT min(c.cantidad) FROM FraterSoftPiaWebBundle:Preciosevento c "
                        . "WHERE c.idevento = " . $idevento . " AND c.cantidad > "
                        . "(select count(i.id) from FraterSoftPiaWebBundle:Inscrito i "
                        . "where i.idevento=" . $idevento . "))"
                )
                ->getResult();
        $preciofecha = $this->getEntityManager()
                ->createQuery(
                        "select p.precio from FraterSoftPiaWebBundle:Preciosevento p "
                        . "where p.idevento=" . $idevento . " and p.hasta = "
                        . "(SELECT min(h.hasta) FROM FraterSoftPiaWebBundle:Preciosevento h "
                        . "WHERE h.idevento = " . $idevento . " AND h.hasta >= CURRENT_TIMESTAMP())"
                )
                ->getResult();
        
        if (!$preciocantidad) //Si el precio por cantidad es nulo, devuelvo precio fecha
            return $preciofecha;
        if(!$preciofecha) //Si el precio por fecha es nulo, devuelvo precio cantidad
            return $preciocantidad;
        if (!$preciocantidad && !$preciofecha) //Si ambos son nulos, devuelvo 0
            return null;
        if ($preciocantidad>=$preciofecha) //Si el precio por cantidad es mayor que el precio por fecha, devuelvo precio cantidad
            return $preciocantidad;
        if($preciofecha>=$preciocantidad) //Si el precio por cantidad es menor que el precio por fecha, devuelvo precio cantidad
            return $preciofecha;
        return null;
    }
    
    public function BuscaPreciosEvento($idevento){
        $precios = $this->getEntityManager()
            ->createQuery(
                    "select p.cantidad, p.precio, p.hasta, p.imagen, p.texto, p.moneda "
                    . "from FraterSoftPiaWebBundle:Preciosevento p "
                    . "where p.idevento = " . $idevento 
                    . " order by p.precio"
            )
            ->getResult();        
        $preciosselect = new ArrayCollection();
        $imagenanterior = "vacio";    
        foreach($precios as $precio){
            switch(true){
                //Solo cantidad configurada
                case !is_null($precio['cantidad']) && is_null($precio['hasta']) && is_null($precio['imagen']):
                    $inscritos = $this->getEntityManager()
                        ->createQuery(
                            "select count(i.id) as inscritos from FraterSoftPiaWebBundle:Inscrito i "
                            . "where i.idevento=" . $idevento . " and i.precio = " . $precio['precio']
                        )
                    ->getResult();
                    if($precio['cantidad']>$inscritos[0]['inscritos']){
                        $preciosselect->add($precio);
                        break 2;
                    }
                    break;
                //Solo fecha configurada
                case is_null($precio['cantidad']) && !is_null($precio['hasta']) && is_null($precio['imagen']):
                    if($precio['hasta'] >= new \DateTime('now')){
                        $preciosselect->add($precio);
                        break 2;
                    }
                    break;
                //Solo imagen configurada
                case is_null($precio['cantidad']) && is_null($precio['hasta']) && !is_null($precio['imagen']):
                    $preciosselect->add($precio);
                    break;
                //Cantidad y fecha configurada
                case !is_null($precio['cantidad']) && !is_null($precio['hasta']) && is_null($precio['imagen']):
                    $inscritos = $this->getEntityManager()
                        ->createQuery(
                            "select count(i.id) as inscritos from FraterSoftPiaWebBundle:Inscrito i "
                            . "where i.idevento=" . $idevento . " and i.precio = " . $precio['precio']
                        )
                    ->getResult();       
                    if($precio['cantidad'] > $inscritos[0]['inscritos'] && $precio['hasta'] >= new \DateTime('now')){
                        $preciosselect->add($precio);
                        break 2;
                    }
                    break;
                //Fecha e imagen configurada
                case is_null($precio['cantidad']) && !is_null($precio['hasta']) && !is_null($precio['imagen']):
                    if($precio['hasta'] >= new \DateTime('now')){
                        $preciosselect->add($precio);
                        break 2;
                    }
                    break;
                //Cantidad e imagen configurada. 
                case !is_null($precio['cantidad']) && is_null($precio['hasta']) && !is_null($precio['imagen']):
                    $inscritos = $this->getEntityManager()
                        ->createQuery(
                            "select count(i.id) as inscritos from FraterSoftPiaWebBundle:Inscrito i "
                            . "where i.idevento=" . $idevento . " and i.precio = " . $precio['precio']
                        )
                    ->getResult(); 
                    if($precio['cantidad'] > $inscritos[0]['inscritos']){
                        if($precio['imagen']!=$imagenanterior){
                            $preciosselect->add($precio);
                            $imagenanterior = $precio['imagen'];
                        }
                    }
                    break;
                //Todos configurados configurados
                case !is_null($precio['cantidad']) && !is_null($precio['hasta']) && !is_null($precio['imagen']):
                    $inscritos = $this->getEntityManager()
                        ->createQuery(
                            "select count(i.id) as inscritos from FraterSoftPiaWebBundle:Inscrito i "
                            . "where i.idevento=" . $idevento . " and i.precio = " . $precio['precio']
                        )
                    ->getResult();       
                    if($precio['cantidad'] > $inscritos[0]['inscritos'] && $precio['hasta'] >= new \DateTime('now')){
                        $preciosselect->add($precio);
                        break 2;
                    }
                    break;
                //Ninguno configurados configurados
                case is_null($precio['cantidad']) && is_null($precio['hasta']) && is_null($precio['imagen']):
                    $preciosselect->add($precio);
                    break;
            }
        }
        return($preciosselect);
    }

    public function arrayPreciosEvento($idevento)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT pe.id,e.id as idevento,pe.precio,pe.cantidad,pe.hasta,pe.prioridad,pe.texto,pe.imagen,pe.moneda '
                    . 'FROM FraterSoftPiaWebBundle:Preciosevento pe ' 
                    . 'JOIN pe.idevento e '                  
                    . 'WHERE pe.idevento =' . $idevento 
            );
         return $query->getResult();
    }          
    
}
