<?php

namespace FraterSoft\PiaWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrecioscategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicidadRepository extends EntityRepository {

    
    public function arrayLista($idevento)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT pu.id,pu.idubicacion,ev.id as idevento,pa.id as idpatrocinante,pa.logo,pa.nombre as patrocinante,pu.estatus '
                    . 'FROM FraterSoftPiaWebBundle:Publicidad pu ' 
                    . 'JOIN pu.idpatrocinante pa '                  
                    . 'JOIN pu.idevento ev '                  
                    . 'WHERE pu.idevento =' . $idevento 
            );
         return $query->getResult();
    }          
    
}
