maestro_organizador:
    pattern:  /organizadores
    defaults: { _controller: "FraterSoftPiaWebBundle:Organizador:index" }

maestro_organizador_new:
    pattern:  /organizadores/new
    defaults: { _controller: "FraterSoftPiaWebBundle:Organizador:new" }

maestro_organizador_create:
    pattern:  /organizadores/create
    defaults: { _controller: "FraterSoftPiaWebBundle:Organizador:create" }
    requirements: { _method: post }

maestro_organizador_edit:
    pattern:  /organizadores/{id}/edit
    defaults: { _controller: "FraterSoftPiaWebBundle:Organizador:edit" }

maestro_organizador_update:
    pattern:  /organizadores/{id}/update
    defaults: { _controller: "FraterSoftPiaWebBundle:Organizador:update" }
    requirements: { _method: post }

maestro_organizador_eliminar:
    pattern:  /organizadores/{id}/eliminar
    defaults: { _controller: "FraterSoftPiaWebBundle:Organizador:eliminar" }
    requirements: { _method: post }

maestro_organizador_formapago_add:
    pattern:  /organizadores/{id}/formaspago/agregar
    defaults: { _controller: "FraterSoftPiaWebBundle:Organizador:formapagoAdd" }
    requirements: { _method: post }

maestro_organizador_formapago_eliminar:
    pattern:  /organizadores/formaspago/{id}/eliminar
    defaults: { _controller: "FraterSoftPiaWebBundle:Organizador:formapagoEliminar" }

maestro_formapago:
    pattern:  /formaspago
    defaults: { _controller: "FraterSoftPiaWebBundle:Formaspago:maestroIndex" }

maestro_formapago_new:
    pattern:  /formaspago/new
    defaults: { _controller: "FraterSoftPiaWebBundle:Formaspago:maestroNew" }

maestro_formapago_create:
    pattern:  /formaspago/create
    defaults: { _controller: "FraterSoftPiaWebBundle:Formaspago:maestroCreate" }
    requirements: { _method: post }

maestro_formapago_edit:
    pattern:  /formaspago/{id}/edit
    defaults: { _controller: "FraterSoftPiaWebBundle:Formaspago:maestroEdit" }

maestro_formapago_update:
    pattern:  /formaspago/{id}/update
    defaults: { _controller: "FraterSoftPiaWebBundle:Formaspago:maestroUpdate" }
    requirements: { _method: post }

maestro_formapago_eliminar:
    pattern:  /formaspago/{id}/eliminar
    defaults: { _controller: "FraterSoftPiaWebBundle:Formaspago:maestroEliminar" }
    requirements: { _method: post }

maestro_formapago_duplicar:
    pattern:  /formaspago/{id}/duplicar
    defaults: { _controller: "FraterSoftPiaWebBundle:Formaspago:maestroDuplicar" }
    requirements: { _method: post }

maestro_moneda:
    pattern:  /monedas
    defaults: { _controller: "FraterSoftPiaWebBundle:Moneda:maestroIndex" }

maestro_moneda_new:
    pattern:  /monedas/new
    defaults: { _controller: "FraterSoftPiaWebBundle:Moneda:maestroNew" }

maestro_moneda_create:
    pattern:  /monedas/create
    defaults: { _controller: "FraterSoftPiaWebBundle:Moneda:maestroCreate" }
    requirements: { _method: post }

maestro_moneda_edit:
    pattern:  /monedas/{id}/edit
    defaults: { _controller: "FraterSoftPiaWebBundle:Moneda:maestroEdit" }

maestro_moneda_update:
    pattern:  /monedas/{id}/update
    defaults: { _controller: "FraterSoftPiaWebBundle:Moneda:maestroUpdate" }
    requirements: { _method: post }

maestro_moneda_eliminar:
    pattern:  /monedas/{id}/eliminar
    defaults: { _controller: "FraterSoftPiaWebBundle:Moneda:maestroEliminar" }
    requirements: { _method: post }
