numeracion_asignar:
    pattern:  /asignar/{idevento}
    defaults: { _controller: "FraterSoftPiaWebBundle:Numeracion:asignar" }
    
numeracion_resetear:
    pattern:  /resetear/{idevento}
    defaults: { _controller: "FraterSoftPiaWebBundle:Numeracion:resetear" }    

numeracion_guardar:
    pattern:  /{idevento}/guardar
    defaults: { _controller: "FraterSoftPiaWebBundle:Numeracion:guardar" }

numeracion_create:
    pattern:  /create
    defaults: { _controller: "FraterSoftPiaWebBundle:Numeracion:create" }
    requirements: { _method: post }

numeracion_update:
    pattern:  /{id}/update
    defaults: { _controller: "FraterSoftPiaWebBundle:Numeracion:update" }
    requirements: { _method: post|put }

numeracion_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "FraterSoftPiaWebBundle:Numeracion:delete" }
    
numeracion_listaajax:
    pattern:  /{idevento}/listaajax
    defaults: { _controller: "FraterSoftPiaWebBundle:Numeracion:listaajax" }
    