organizador_guardar:
    pattern:  /{email}/guardar
    defaults: { _controller: "FraterSoftPiaWebBundle:Organizador:guardar" }    

organizador_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "FraterSoftPiaWebBundle:Organizador:delete" }
    