publicidad_guardar:
    pattern:  /{idevento}/guardar
    defaults: { _controller: "FraterSoftPiaWebBundle:Organizador:guardar" }    

publicidad_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "FraterSoftPiaWebBundle:Organizador:delete" }
    