tema_guardar:
    pattern:  /{idevento}/guardar
    defaults: { _controller: "FraterSoftPiaWebBundle:Tema:guardar" }    

tema_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "FraterSoftPiaWebBundle:Tema:delete" }
    