FraterSoft\PiaWebBundle\Entity\Ciudad:
    type: entity
    table: piaaccess.tmciudades
    indexes:
        IDX_7AEDD9E242E04C4F:
            columns:
                - idestado
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombre:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
    manyToOne:
        idestado:
            targetEntity: Estado
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idestado:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
