FraterSoft\PiaWebBundle\Entity\Competidor:
    type: entity
    table: piaaccess.tmcompetidores
    repositoryClass: FraterSoft\PiaWebBundle\Entity\CompetidorRepository     
    indexes:
        IDX_AAAA86342E04C4F:
            columns:
                - idestado
    uniqueConstraints:
        tmcompetidores_emailpersonal_un:
            columns:
                - emailpersonal
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        iddocumento:
            type: string
            nullable: true
            length: 20
            fixed: false
            comment: ''
        nombre:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
        apellido:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
        foto:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        fechanacimiento:
            type: datetime
            nullable: true
            comment: ''
        sexo:
            type: string
            nullable: true
            length: 1
            fixed: false
            comment: ''
        equipo:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        edad:
            type: bigint
            nullable: true
            unsigned: false
            comment: ''
        peso:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
        email:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        telefono:
            type: string
            nullable: true
            length: 15
            fixed: false
            comment: ''
        idpais:
            type: bigint
            nullable: true
            unsigned: false
            comment: ''
        tallafranela:
            type: string
            nullable: true
            length: 5
            fixed: false
            comment: ''
        certificado:
            type: boolean
            nullable: true
            comment: ''
        publicado:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        fechapublicacion:
            type: date
            nullable: true
            comment: ''
        idrepresentante:
            type: string
            nullable: true
            length: 20
            fixed: false
            comment: ''
        nombrerepresentante:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        emailpersonal:
            type: string
            unique: true
            nullable: true
            length: 254
            fixed: false
            comment: ''
        estadocivil:
            type: string
            nullable: true
            length: 1
            fixed: false
            comment: "C=CASADO\nS=SOLTERO\nD=DIVORCIADO\nV=VIUDO\nO=OTRO\n"
        estatura:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
        gruposanguineo:
            type: string
            nullable: true
            length: 9
            fixed: false
            comment: ''
        alergicoa:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: 'Si el campo esta vacio, no es alergico a ningun elemento'
        direccion:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        tallamono:
            type: string
            nullable: true
            length: 5
            fixed: false
            comment: ''
        tallazapatos:
            type: string
            nullable: true
            length: 5
            fixed: true
            comment: ''
        tallachaqueta:
            type: string
            nullable: true
            length: 5
            fixed: true
            comment: ''
        tallachemis:
            type: string
            nullable: true
            length: 5
            fixed: false
            comment: ''
        tallaguantes:
            type: string
            nullable: true
            length: 5
            fixed: false
            comment: ''
        entrenador:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        fileiddocumento:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        filepartidanacimiento:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        filecertificadodeportivo:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        textodorsal:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        telefonoemergencia:
            type: string
            nullable: true
            length: 20
            fixed: false
            comment: ''
        seguromedico:
            type: string
            nullable: true
            length: 2
            fixed: false
            comment: ''
    manyToOne:
        idestado:
            targetEntity: Estado
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idestado:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
