FraterSoft\PiaWebBundle\Entity\Evento:
    type: entity
    table: piaaccess.tmeventos
    repositoryClass: FraterSoft\PiaWebBundle\Entity\EventoRepository       
    indexes:
        IDX_1B29C54DEA3BA832:
            columns:
                - idciudad
        IDX_1B29C54D6FAFBFF6:
            columns:
                - idorganizador
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombre:
            type: string
            nullable: true
            length: 40
            fixed: false
            comment: ''
        logo:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        fecha:
            type: datetime
            nullable: true
            comment: ''
        hora:
            type: datetime
            nullable: true
            comment: ''
        lugar:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        ruta:
            type: blob
            nullable: true
            length: null
            fixed: false
            comment: ''
        organizador:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
        nombrecontacto:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
        telefonocontacto:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
        puntoinscripcion:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: ''
        fechacierre:
            type: datetime
            nullable: true
            comment: ''
        fechacierreefectivo:
            type: datetime
            nullable: true
            comment: ''
        horacierre:
            type: datetime
            nullable: true
            comment: ''
        equipo:
            type: string
            nullable: true
            length: 20
            fixed: false
            comment: ''
        rifa:
            type: boolean
            nullable: true
            comment: ''
        tipo:
            type: string
            nullable: true
            length: 1
            fixed: false
            comment: ''
        cupocontrol:
            type: boolean
            nullable: true
            comment: ''
        cupomaximo:
            type: bigint
            nullable: true
            unsigned: false
            comment: ''
        activo:
            type: boolean
            nullable: true
            comment: ''
        #idcampeonato:
        #    type: bigint
        #    nullable: true
        #    unsigned: false
        #    comment: ''
        criteriocalculoedad:
            type: integer
            nullable: true
            unsigned: false
            comment: "1: Calculo Edad Calendario = Anio Actual - Anio Fecha de Nacimiento\n\n2: Calculo Edad Al Evento = \n\n               Si FechaNacimiento < FechaEvento \n\n                             Anio Actual - Anio Fecha de Nacimiento - 1\n\n               Si FechaNacimiento >= FechaEvento \n\n                             Anio Actual - Anio Fecha de Nacimiento"
        controlamenores16:
            type: boolean
            nullable: true
            comment: ''
        emailcontacto:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: ''
        fechainicio:
            type: datetimetz
            nullable: true
            comment: ''
        zonahoraria:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        url:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: 'URL de eventos externos al sistema'
        externo:
            type: boolean
            nullable: false
            comment: ''
            default: false
        clasificacion:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        rutamapa:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        rutaperfil:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        rutavideo:
            type: string
            nullable: true
            length: 300
            fixed: false
            comment: ''
        inforepresentante:
            type: boolean
            nullable: true
            comment: ''
            default: false
        proceso:
            type: integer
            nullable: true
            unsigned: false
            comment: "Indica el tipo de proceso que se manejara en el evento.\n\n1: Proceso por Defecto, el usuario debe realizar la transferencia antes de preinscribirse. 2: El proceso de pre-inscripcion no requiere de pago, el pago es ingresado el fechas posteriores"
            default: '1'
        mapalugar:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: ''
        registropago:
            type: integer
            nullable: true
            unsigned: false
            comment: "Indica si el pago lo registra el participante o el organizaodor\nValores posibles: 1 el pago lo registra el participante, 2 el pago lo registra el organizador"
    manyToOne:
        idorganizador:
            targetEntity: Organizador
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idorganizador:
                    referencedColumnName: id
            orphanRemoval: false
        idcampeonato:
            targetEntity: Campeonato
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idcampeonato:
                    referencedColumnName: id
            orphanRemoval: false            
        idciudad:
            targetEntity: Ciudad
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idciudad:
                    referencedColumnName: id
            orphanRemoval: false            
    oneToOne:
      tema:
        targetEntity: Tema
        mappedBy: idevento            
      numeracion:
        targetEntity: Numeracion
        mappedBy: idevento  
    manyToMany:
        idrecarga:
            targetEntity: Recarga
            cascade: { }
            mappedBy: null
            inversedBy: idevento
            joinTable:
                name: piaaccess.treventosrecargas
                joinColumns:
                    -
                        name: idevento
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: idrecarga
                        referencedColumnName: id
            orderBy: null        
    oneToMany:
        atributos:
            targetEntity: EventoAtributos
            mappedBy: idevento
            orderBy: { 'orden': 'ASC' }
    lifecycleCallbacks: {  }
