FraterSoft\PiaWebBundle\Entity\Formaspago:
    type: entity
    table: piaaccess.tmformaspagos
    repositoryClass: FraterSoft\PiaWebBundle\Entity\FormaspagoRepository
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombre:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        status:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        icono:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        parametros:
            type: string
            nullable: true
            length: 500
            fixed: false
            comment: ''
        programa:
            type: string
            nullable: true
            length: 500
            fixed: false
            comment: ''
        verificable:
            type: boolean
            nullable: false
            comment: 'Determina si el pago realizado con la forma de pago seleccionada, debe ser verificado en el distino del pago'    
    manyToOne:
        idmoneda:
            targetEntity: Moneda
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idmoneda:
                    referencedColumnName: id
            orphanRemoval: false
lifecycleCallbacks: {  }
