FraterSoft\PiaWebBundle\Entity\Formaspago:
    type: entity
    table: piaaccess.tmformaspagos
    repositoryClass: FraterSoft\PiaWebBundle\Entity\FormaspagoRepository
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombre:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        status:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
    lifecycleCallbacks: {  }
