FraterSoft\PiaWebBundle\Entity\Pago:
    type: entity
    table: piaaccess.tmpagos
    repositoryClass: FraterSoft\PiaWebBundle\Entity\PagoRepository        
    indexes:
        IDX_E658DD60F4F43B:
            columns:
                - idformapago
        IDX_E658DD60A1DB8DC8:
            columns:
                - idbanco
        IDX_E658DD60D4B68681:
            columns:
                - idmoneda
        IDX_E658DD609890313D:
            columns:
                - idinscrito
        IDX_E658DD60557A1263:
            columns:
                - idcuenta
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        fechahora:
            type: datetime
            nullable: true
            comment: ''
        monto:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
        moneda:
            type: string
            nullable: true
            length: 3
            fixed: false
            comment: ''
        referencia:
            type: string
            nullable: true
            length: 20
            fixed: false
            comment: ''
        comprobante:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: 'Almacena la ruta y el nombre del archivo del comprobante'
        tipo:
            type: string
            nullable: true
            length: 20
            fixed: false
            comment: ''
        banco:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        conciliado:
            type: boolean
            nullable: true
            comment: ''
        conciliadoel:
            type: datetime
            nullable: true
            comment: ''
        idliquidacion:
            type: bigint
            nullable: true
            unsigned: false
            comment: ''
        notificado:
            type: datetime
            nullable: true
            comment: ''
        texto:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        idpagador:
            type: string
            nullable: true
            length: 20
            fixed: false
            comment: ''
        nombrepagador:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        correopagador:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        fechapago:
            type: date
            nullable: true
            comment: 'Es la fecha en la que el participante realizo el pago'
        precio:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
        recargas:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
    manyToOne:
        idformapago:
            targetEntity: Formaspago
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idformapago:
                    referencedColumnName: id
            orphanRemoval: false
        idbanco:
            targetEntity: Banco
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idbanco:
                    referencedColumnName: id
            orphanRemoval: false
        idmoneda:
            targetEntity: Moneda
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idmoneda:
                    referencedColumnName: id
            orphanRemoval: false
        idinscrito:
            targetEntity: Inscrito
            cascade: {  }
            mappedBy: null
            inversedBy: pagos
            joinColumns:
                idinscrito:
                    referencedColumnName: id
            orphanRemoval: false
        idcuenta:
            targetEntity: Organizadorcuentas
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idcuenta:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
