FraterSoft\PiaWebBundle\Entity\Preciosevento:
    type: entity
    table: piaaccess.tmprecioseventos
    repositoryClass: FraterSoft\PiaWebBundle\Entity\PrecioseventoRepository           
    indexes:
        IDX_7F7FC412233BA6A9:
            columns:
                - idevento
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        precio:
            type: float
            nullable: true
            precision: 10
            scale: 0
            comment: ''
        cantidad:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        hasta:
            type: datetime
            nullable: true
            comment: 'Guarda la fecha hasta donde se asignara dicho precio'
        prioridad:
            type: string
            nullable: true
            length: 15
            fixed: false
            comment: 'Determina cual de los dos factores (cantidad o fecha hasta) sera tomado primero en cuenta cuando se configuren ambos parametros'
        texto:
            type: string
            nullable: true
            length: 100
            fixed: false
        imagen:
            type: string
            nullable: true
            length: 300
            fixed: false
            comment: 'Se usa para mostrar las imagenes de las opciones que incluyen el precio'
        moneda:
            type: string
            nullable: true
            length: 5
            fixed: false
    manyToOne:
        idevento:
            targetEntity: Evento
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idevento:
                    referencedColumnName: id
        idmoneda:
            targetEntity: Moneda
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idmoneda:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
